
trigger:
  branches:
    include:
    - main
    - dev
    - feature/*

  paths:
    include: 
    - src

stages: 
  - template: ../templates/yaml/environments.yml
    parameters:
      buildTemplatePath: ../../pipelines/build/build.yml
      deployTemplatePath: ../../pipelines/deploy/deploy.yml
